package com.tw;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.LinkedList;

import static org.junit.Assert.*;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class LibraryTest {
    private Menu menu;
    private ByteArrayOutputStream outContent = new ByteArrayOutputStream();

    @Before
    public void beforeEach(){
        menu = new Menu();
        System.setOut(new PrintStream(outContent));
    }

    @Test
    public void should_return_menu(){
        assertEquals("1. 添加学生\n" +
                "2. 生成成绩单\n" +
                "3. 退出\n" +
                "请输入你的选择（1～3）：\n",menu.printMainMenu());
    }

    @Test
    public void should_retuen_false_when_add_student(){
//       student id is wrong
        String input = "张三，a，数学：95，语文：90，英语：88，编程：89";
        assertFalse(menu.judgeAddStudentFormat(input));
//        no student name
        input = "12，数学：95，语文：90，英语：88，编程：89";
        assertFalse(menu.judgeAddStudentFormat(input));
//        wrong grade
        input = "张三，12，数学：95，语文：90a，英语：88，编程：89";
        assertFalse(menu.judgeAddStudentFormat(input));
//        wrong grade
        input = "张三，12，数学：95，语文：90，英语：188，编程：89";
        assertFalse(menu.judgeAddStudentFormat(input));
//        wrong grade
        input = "张三，12，数学：95，语文：90，英语：88，编程：-89";
        assertFalse(menu.judgeAddStudentFormat(input));
//        wrong grade
        input = "张三，12，数学：95，英语：188，编程：89";
        assertFalse(menu.judgeAddStudentFormat(input));
//        wrong format
        input = "张三：12，数学：95，语文：90，英语：88，编程：89";
        assertFalse(menu.judgeAddStudentFormat(input));
    }

    @Test
    public void should_retuen_true_when_add_student(){
        String input = "张三，12，数学：95，语文：90，英语：88，编程：89";
        assertTrue(menu.judgeAddStudentFormat(input));
    }

    @Test
    public void should_return_false_when_print_grade(){
        String input = "12a";
        assertFalse(menu.judgePrintGradeFormat(input));
        input = "1;2";
        assertFalse(menu.judgePrintGradeFormat(input));
        input ="1.2,3";
        assertFalse(menu.judgePrintGradeFormat(input));
    }

    @Test
    public void should_return_true_when_print_grade(){
        String input = "12,13";
        assertTrue(menu.judgePrintGradeFormat(input));
        input = "1";
        assertTrue(menu.judgePrintGradeFormat(input));
    }

}
